/**
 * Command Code Provider API model catalog.
 *
 * The static metadata supplies capabilities and local cost estimates. The
 * public `/provider/v1/models` endpoint supplies live names, context windows,
 * and endpoint support; it is used by the provider's normal model refresh.
 *
 * Capability and pricing metadata is a checked-in snapshot because the live
 * model endpoint does not provide those fields. Refresh it when the official
 * model list or pricing changes.
 *
 * Captured: 2026-09-23 (77 models).
 */

import type { Model, ThinkingLevelMap } from "@myharness/ai";

export const COMMAND_CODE_PROVIDER_ID = "command-code";
export const COMMAND_CODE_OPENAI_BASE_URL = "https://api.commandcode.ai/provider/v1";
export const COMMAND_CODE_ANTHROPIC_BASE_URL = "https://api.commandcode.ai/provider";
export const COMMAND_CODE_MODELS_URL = `${COMMAND_CODE_OPENAI_BASE_URL}/models`;

export type CommandCodeApi = "openai-completions" | "anthropic-messages";

export interface CommandCodeCatalogEntry {
	id: string;
	name: string;
	/** Upstream family used for display grouping. */
	group: string;
	description: string;
	contextWindow: number;
	maxTokens: number;
	reasoning: boolean;
	input: ("text" | "image")[];
	cost: { input: number; output: number; cacheRead: number; cacheWrite: number };
	thinkingLevelMap?: ThinkingLevelMap;
}

/** Verified catalog of models the platform serves on account credits. */
export const COMMAND_CODE_CATALOG: readonly CommandCodeCatalogEntry[] = [
	{
		id: "deepseek/deepseek-v4-pro",
		name: "DeepSeek V4 Pro (latest)",
		group: "Open Source",
		description: "hybrid-attention long-context reasoning",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text"],
		cost: { input: 0.66, output: 1.98, cacheRead: 0.022, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: null, medium: null, high: "high", xhigh: null, max: "max" },
	},
	{
		id: "deepseek/deepseek-v4-flash",
		name: "DeepSeek V4 Flash (latest)",
		group: "Open Source",
		description: "fast hybrid-attention reasoning",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text"],
		cost: { input: 0.15, output: 0.6, cacheRead: 0.003, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: null, medium: null, high: "high", xhigh: null, max: "max" },
	},
	{
		id: "deepseek/deepseek-v4-flash-vision-exp",
		name: "DeepSeek V4 Flash Vision (exp)",
		group: "Open Source",
		description: "fast hybrid-attention reasoning with vision",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 0.15, output: 0.6, cacheRead: 0.003, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: null, medium: null, high: "high", xhigh: null, max: "max" },
	},
	{
		id: "deepseek/deepseek-v4-flash-fast",
		name: "DeepSeek V4 Flash Fast",
		group: "Open Source",
		description: "low-latency V4 Flash deployment",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text"],
		cost: { input: 0.28, output: 0.56, cacheRead: 0.07, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: null, high: "high", xhigh: null, max: "max" },
	},
	{
		id: "deepseek/deepseek-v4.1-flash",
		name: "DeepSeek V4.1 Flash",
		group: "Open Source",
		description: "V4.1 hybrid-attention reasoning with vision",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 0.15, output: 0.6, cacheRead: 0.003, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: null, high: "high", xhigh: null, max: "max" },
	},
	{
		id: "moonshotai/Kimi-K3",
		name: "Kimi K3",
		group: "Open Source",
		description: "long-horizon coding & knowledge work with 1M context",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: null, high: "high", xhigh: null, max: "max" },
	},
	{
		id: "moonshotai/Kimi-K2.7-Code",
		name: "Kimi K2.7 Code",
		group: "Open Source",
		description: "improved long-horizon coding with vision",
		contextWindow: 256000,
		maxTokens: 64000,
		reasoning: false,
		input: ["text", "image"],
		cost: { input: 0.95, output: 4, cacheRead: 0.19, cacheWrite: 0 },
		thinkingLevelMap: undefined,
	},
	{
		id: "moonshotai/Kimi-K2.7-Code-Highspeed",
		name: "Kimi K2.7 Code HighSpeed",
		group: "Open Source",
		description: "high-speed long-horizon coding with vision",
		contextWindow: 262000,
		maxTokens: 64000,
		reasoning: false,
		input: ["text", "image"],
		cost: { input: 1.9, output: 8, cacheRead: 0.38, cacheWrite: 0 },
		thinkingLevelMap: undefined,
	},
	{
		id: "moonshotai/Kimi-K2.6",
		name: "Kimi K2.6",
		group: "Open Source",
		description: "long-horizon coding with vision",
		contextWindow: 256000,
		maxTokens: 64000,
		reasoning: false,
		input: ["text", "image"],
		cost: { input: 0.95, output: 4, cacheRead: 0.16, cacheWrite: 0 },
		thinkingLevelMap: undefined,
	},
	{
		id: "moonshotai/Kimi-K2.5",
		name: "Kimi K2.5",
		group: "Open Source",
		description: "multimodal frontend coding",
		contextWindow: 256000,
		maxTokens: 64000,
		reasoning: false,
		input: ["text", "image"],
		cost: { input: 0.6, output: 3, cacheRead: 0.1, cacheWrite: 0 },
		thinkingLevelMap: undefined,
	},
	{
		id: "z-ai/glm-5.3-flash",
		name: "GLM-5.3 Flash",
		group: "Open Source",
		description: "fast, affordable GLM coding with 1M context",
		contextWindow: 1048576,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 0.15, output: 0.5, cacheRead: 0.03, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: null, high: "high", xhigh: null, max: "max" },
	},
	{
		id: "z-ai/glm-5.3-flashx",
		name: "GLM-5.3 FlashX",
		group: "Open Source",
		description: "high-speed GLM-5.3 Flash with 1M context",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 0.37, output: 1.25, cacheRead: 0.075, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: null, high: "high", xhigh: null, max: "max" },
	},
	{
		id: "zai-org/GLM-5.3",
		name: "GLM-5.3",
		group: "Open Source",
		description: "frontier coding with emergent cyber capabilities",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text"],
		cost: { input: 1.4, output: 4.4, cacheRead: 0.26, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: null, high: "high", xhigh: null, max: "max" },
	},
	{
		id: "zai-org/GLM-5.2",
		name: "GLM-5.2",
		group: "Open Source",
		description: "powerful coding with 1M context and long-horizon tasks",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text"],
		cost: { input: 1.4, output: 4.4, cacheRead: 0.26, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: null, medium: null, high: "high", xhigh: null, max: "max" },
	},
	{
		id: "zai-org/GLM-5.2-Fast",
		name: "GLM-5.2 Fast",
		group: "Open Source",
		description: "high-throughput GLM-5.2 with 1M context",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: false,
		input: ["text"],
		cost: { input: 3, output: 10.25, cacheRead: 0.5, cacheWrite: 0 },
		thinkingLevelMap: undefined,
	},
	{
		id: "zai-org/GLM-5.1",
		name: "GLM-5.1",
		group: "Open Source",
		description: "long-horizon autonomous coding agent",
		contextWindow: 200000,
		maxTokens: 64000,
		reasoning: false,
		input: ["text"],
		cost: { input: 1.4, output: 4.4, cacheRead: 0.26, cacheWrite: 0 },
		thinkingLevelMap: undefined,
	},
	{
		id: "zai-org/GLM-5",
		name: "GLM-5",
		group: "Open Source",
		description: "multi-mode thinking & long-range planning",
		contextWindow: 200000,
		maxTokens: 64000,
		reasoning: false,
		input: ["text"],
		cost: { input: 1, output: 3.2, cacheRead: 0.2, cacheWrite: 0 },
		thinkingLevelMap: undefined,
	},
	{
		id: "MiniMaxAI/MiniMax-M3",
		name: "MiniMax M3",
		group: "Open Source",
		description: "frontier coding, agents & native multimodality",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 0.3, output: 1.2, cacheRead: 0.06, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: null, max: null },
	},
	{
		id: "MiniMaxAI/MiniMax-M2.7",
		name: "MiniMax M2.7",
		group: "Open Source",
		description: "end-to-end software engineering agent",
		contextWindow: 200000,
		maxTokens: 64000,
		reasoning: false,
		input: ["text"],
		cost: { input: 0.3, output: 1.2, cacheRead: 0.06, cacheWrite: 0 },
		thinkingLevelMap: undefined,
	},
	{
		id: "MiniMaxAI/MiniMax-M2.5",
		name: "MiniMax M2.5",
		group: "Open Source",
		description: "cross-platform full-stack agentic dev",
		contextWindow: 200000,
		maxTokens: 64000,
		reasoning: false,
		input: ["text"],
		cost: { input: 0.3, output: 1.2, cacheRead: 0.03, cacheWrite: 0 },
		thinkingLevelMap: undefined,
	},
	{
		id: "xiaomi/mimo-v2.6-pro",
		name: "MiMo V2.6 Pro",
		group: "Open Source",
		description: "flagship multimodal agentic coding with 1M context",
		contextWindow: 1048576,
		maxTokens: 64000,
		reasoning: false,
		input: ["text", "image"],
		cost: { input: 0.435, output: 0.87, cacheRead: 0.0036, cacheWrite: 0 },
		thinkingLevelMap: undefined,
	},
	{
		id: "xiaomi/mimo-v2.6-pro-ultraspeed",
		name: "MiMo V2.6 Pro UltraSpeed",
		group: "Open Source",
		description: "low-latency serving tier of MiMo V2.6 Pro",
		contextWindow: 1048576,
		maxTokens: 64000,
		reasoning: false,
		input: ["text", "image"],
		cost: { input: 4.35, output: 8.7, cacheRead: 0.036, cacheWrite: 0 },
		thinkingLevelMap: undefined,
	},
	{
		id: "xiaomi/mimo-v2.6-flash",
		name: "MiMo V2.6 Flash",
		group: "Open Source",
		description: "efficient multimodal agentic coding with 1M context",
		contextWindow: 1048576,
		maxTokens: 64000,
		reasoning: false,
		input: ["text", "image"],
		cost: { input: 0.14, output: 0.28, cacheRead: 0.0028, cacheWrite: 0 },
		thinkingLevelMap: undefined,
	},
	{
		id: "xiaomi/mimo-v2.5-pro",
		name: "MiMo V2.5 Pro",
		group: "Open Source",
		description: "high-capability long-context agentic coding",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: false,
		input: ["text"],
		cost: { input: 0.435, output: 0.87, cacheRead: 0.0036, cacheWrite: 0 },
		thinkingLevelMap: undefined,
	},
	{
		id: "xiaomi/mimo-v2.5",
		name: "MiMo V2.5",
		group: "Open Source",
		description: "efficient long-context agentic coding",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: false,
		input: ["text", "image"],
		cost: { input: 0.14, output: 0.28, cacheRead: 0.0028, cacheWrite: 0 },
		thinkingLevelMap: undefined,
	},
	{
		id: "Qwen/Qwen3.8-Omni-Flash",
		name: "Qwen 3.8 Omni Flash",
		group: "Open Source",
		description: "omni-modal understanding & multimedia agentic work",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 0.15, output: 0.47, cacheRead: 0.016, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: null, xhigh: "xhigh", max: null },
	},
	{
		id: "Qwen/Qwen3.8-Max-0902",
		name: "Qwen 3.8 Max 0902",
		group: "Open Source",
		description: "upgraded Qwen 3.8 Max: stronger coding & agentic tool use",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 2, output: 6, cacheRead: 0.25, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: null, xhigh: "xhigh", max: null },
	},
	{
		id: "Qwen/Qwen3.8-Max",
		name: "Qwen 3.8 Max",
		group: "Open Source",
		description: "autonomous long-horizon coding & professional work",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 2, output: 6, cacheRead: 0.25, cacheWrite: 2.5 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: null, xhigh: "xhigh", max: null },
	},
	{
		id: "Qwen/Qwen3.8-27B",
		name: "Qwen 3.8 27B",
		group: "Open Source",
		description: "compact vision-language coding & agentic work",
		contextWindow: 262144,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 0.4, output: 3, cacheRead: 0.04, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: null, xhigh: "xhigh", max: null },
	},
	{
		id: "Qwen/Qwen3.8-Flash",
		name: "Qwen 3.8 Flash",
		group: "Open Source",
		description: "fast low-cost agentic coding & reasoning",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 0.16, output: 0.47, cacheRead: 0.016, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: null, xhigh: "xhigh", max: null },
	},
	{
		id: "Qwen/Qwen3.7-Max",
		name: "Qwen 3.7 Max",
		group: "Open Source",
		description: "frontier coding & long-horizon agent execution",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: false,
		input: ["text"],
		cost: { input: 2.5, output: 7.5, cacheRead: 0.5, cacheWrite: 3.13 },
		thinkingLevelMap: undefined,
	},
	{
		id: "Qwen/Qwen3.7-Plus",
		name: "Qwen 3.7 Plus",
		group: "Open Source",
		description: "agentic coding & reasoning at lower cost",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: false,
		input: ["text", "image"],
		cost: { input: 0.4, output: 1.6, cacheRead: 0.08, cacheWrite: 0.5 },
		thinkingLevelMap: undefined,
	},
	{
		id: "Qwen/Qwen3.7-Flash",
		name: "Qwen 3.7 Flash",
		group: "Open Source",
		description: "fast low-cost agentic coding & reasoning",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: false,
		input: ["text", "image"],
		cost: { input: 0.03, output: 0.13, cacheRead: 0.006, cacheWrite: 0.038 },
		thinkingLevelMap: undefined,
	},
	{
		id: "Qwen/Qwen3.6-Max-Preview",
		name: "Qwen 3.6 Max Preview",
		group: "Open Source",
		description: "vibe coding & efficient agent execution",
		contextWindow: 200000,
		maxTokens: 64000,
		reasoning: false,
		input: ["text"],
		cost: { input: 1.3, output: 7.8, cacheRead: 0.26, cacheWrite: 1.63 },
		thinkingLevelMap: undefined,
	},
	{
		id: "Qwen/Qwen3.6-Plus",
		name: "Qwen 3.6 Plus",
		group: "Open Source",
		description: "agentic coding & reasoning",
		contextWindow: 200000,
		maxTokens: 64000,
		reasoning: false,
		input: ["text", "image"],
		cost: { input: 0.5, output: 3, cacheRead: 0.1, cacheWrite: 0 },
		thinkingLevelMap: undefined,
	},
	{
		id: "meituan/LongCat-2.0",
		name: "LongCat 2.0",
		group: "Open Source",
		description: "trillion-parameter agentic coding with 1M context",
		contextWindow: 1048576,
		maxTokens: 64000,
		reasoning: false,
		input: ["text"],
		cost: { input: 0.3, output: 1.2, cacheRead: 0.006, cacheWrite: 0 },
		thinkingLevelMap: undefined,
	},
	{
		id: "stepfun/Step-5-Preview",
		name: "Step 5 Preview",
		group: "Open Source",
		description: "600B sparse-MoE agentic coding with 1M context",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 1, output: 2.7, cacheRead: 0.05, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: null, max: null },
	},
	{
		id: "stepfun/Step-3.7-Flash",
		name: "Step 3.7 Flash",
		group: "Open Source",
		description: "multimodal sparse-MoE reasoning",
		contextWindow: 256000,
		maxTokens: 64000,
		reasoning: false,
		input: ["text", "image"],
		cost: { input: 0.2, output: 1.15, cacheRead: 0.04, cacheWrite: 0 },
		thinkingLevelMap: undefined,
	},
	{
		id: "stepfun/Step-3.5-Flash",
		name: "Step 3.5 Flash",
		group: "Open Source",
		description: "fast sparse-MoE agentic reasoning",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: false,
		input: ["text"],
		cost: { input: 0.1, output: 0.3, cacheRead: 0.02, cacheWrite: 0 },
		thinkingLevelMap: undefined,
	},
	{
		id: "tencent/hy3-paid",
		name: "Tencent Hy3",
		group: "Open Source",
		description: "sparse-MoE reasoning & agentic tool use",
		contextWindow: 262144,
		maxTokens: 64000,
		reasoning: false,
		input: ["text"],
		cost: { input: 0.14, output: 0.58, cacheRead: 0.035, cacheWrite: 0 },
		thinkingLevelMap: undefined,
	},
	{
		id: "tencent/hy4-preview",
		name: "Tencent Hy4 Preview",
		group: "Open Source",
		description: "agentic coding & sustained multi-step tool use",
		contextWindow: 1048576,
		maxTokens: 64000,
		reasoning: true,
		input: ["text"],
		cost: { input: 0.834, output: 2.501, cacheRead: 0.042, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: null, max: null },
	},
	{
		id: "nvidia/nemotron-3-ultra-550b-a55b",
		name: "Nemotron 3 Ultra",
		group: "Open Source",
		description: "open reasoning model for long-horizon autonomous agents",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: false,
		input: ["text"],
		cost: { input: 0.6, output: 2.4, cacheRead: 0.12, cacheWrite: 0 },
		thinkingLevelMap: undefined,
	},
	{
		id: "thinkingmachines/inkling",
		name: "Inkling",
		group: "Open Source",
		description: "multimodal MoE reasoning",
		contextWindow: 256000,
		maxTokens: 64000,
		reasoning: false,
		input: ["text", "image"],
		cost: { input: 1, output: 4.05, cacheRead: 0.17, cacheWrite: 0 },
		thinkingLevelMap: undefined,
	},
	{
		id: "thinkingmachines/inkling-small",
		name: "Inkling Small",
		group: "Open Source",
		description: "lightweight MoE reasoning at lower cost and latency",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: false,
		input: ["text", "image"],
		cost: { input: 0.5, output: 1.2, cacheRead: 0.1, cacheWrite: 0 },
		thinkingLevelMap: undefined,
	},
	{
		id: "poolside/laguna-s-2.1-free",
		name: "Laguna S 2.1",
		group: "Open Source",
		description: "open-weight agentic coding and long-horizon work",
		contextWindow: 256000,
		maxTokens: 64000,
		reasoning: false,
		input: ["text"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		thinkingLevelMap: undefined,
	},
	{
		id: "inclusionai/ling-3.0-flash-sante:free",
		name: "Ling 3.0 Flash Sante",
		group: "Open Source",
		description: "health & medicine tuned lightweight-MoE, still strong on code",
		contextWindow: 262144,
		maxTokens: 64000,
		reasoning: false,
		input: ["text"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		thinkingLevelMap: undefined,
	},
	{
		id: "claude-sonnet-5",
		name: "Claude Sonnet 5",
		group: "Anthropic",
		description: "best combo of speed & intelligence (recommended)",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 2, output: 10, cacheRead: 0.2, cacheWrite: 2.5 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: "xhigh", max: "max" },
	},
	{
		id: "claude-sonnet-4-6",
		name: "Claude Sonnet 4.6",
		group: "Anthropic",
		description: "prev Sonnet, still fast & capable",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 3.75 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: "xhigh", max: "max" },
	},
	{
		id: "claude-fable-5-1",
		name: "Claude Fable 5.1",
		group: "Anthropic",
		description: "most capable for demanding reasoning & long-horizon agents",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 10, output: 50, cacheRead: 0.25, cacheWrite: 12.5 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: "xhigh", max: "max" },
	},
	{
		id: "claude-fable-5",
		name: "Claude Fable 5",
		group: "Anthropic",
		description: "prev Fable, still strong for deep reasoning & agents",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 10, output: 50, cacheRead: 1, cacheWrite: 12.5 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: "xhigh", max: "max" },
	},
	{
		id: "claude-opus-5-5",
		name: "Claude Opus 5.5",
		group: "Anthropic",
		description: "latest Claude Opus model for demanding reasoning and agent workflows",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 4, output: 20, cacheRead: 0.2, cacheWrite: 5 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: "xhigh", max: "max" },
	},
	{
		id: "claude-opus-5",
		name: "Claude Opus 5",
		group: "Anthropic",
		description: "most intelligent Opus for agents and coding",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: "xhigh", max: "max" },
	},
	{
		id: "claude-opus-4-8",
		name: "Claude Opus 4.8",
		group: "Anthropic",
		description: "prev flagship, still strong for agents and coding",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: "xhigh", max: "max" },
	},
	{
		id: "claude-opus-4-7",
		name: "Claude Opus 4.7",
		group: "Anthropic",
		description: "older Opus, still strong for agents and coding",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: "xhigh", max: "max" },
	},
	{
		id: "claude-haiku-4-5-20251001",
		name: "Claude Haiku 4.5",
		group: "Anthropic",
		description: "fastest & most compact, great for quick tasks",
		contextWindow: 200000,
		maxTokens: 64000,
		reasoning: false,
		input: ["text", "image"],
		cost: { input: 1, output: 5, cacheRead: 0.1, cacheWrite: 1.25 },
		thinkingLevelMap: undefined,
	},
	{
		id: "gpt-5.6-sol",
		name: "GPT-5.6 Sol",
		group: "OpenAI",
		description: "frontier model for complex professional work",
		contextWindow: 1050000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 6.25 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: "xhigh", max: "max" },
	},
	{
		id: "gpt-5.6-terra",
		name: "GPT-5.6 Terra",
		group: "OpenAI",
		description: "balances intelligence and cost",
		contextWindow: 1050000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 2, output: 12, cacheRead: 0.2, cacheWrite: 2.5 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: "xhigh", max: "max" },
	},
	{
		id: "gpt-5.6-luna",
		name: "GPT-5.6 Luna",
		group: "OpenAI",
		description: "optimized for cost-sensitive workloads",
		contextWindow: 1050000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 0.2, output: 1.2, cacheRead: 0.02, cacheWrite: 0.25 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: "xhigh", max: "max" },
	},
	{
		id: "gpt-5.5",
		name: "GPT-5.5",
		group: "OpenAI",
		description: "latest frontier model for general complex work",
		contextWindow: 400000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: "xhigh", max: null },
	},
	{
		id: "gpt-5.4",
		name: "GPT-5.4",
		group: "OpenAI",
		description: "frontier model for general complex work",
		contextWindow: 400000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 2.5, output: 15, cacheRead: 0.25, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: "xhigh", max: null },
	},
	{
		id: "gpt-5.3-codex",
		name: "GPT-5.3 Codex",
		group: "OpenAI",
		description: "frontier coding model",
		contextWindow: 400000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 2, output: 8, cacheRead: 0.5, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: "xhigh", max: null },
	},
	{
		id: "gpt-5.4-mini",
		name: "GPT-5.4 Mini",
		group: "OpenAI",
		description: "fast, cost-effective model for everyday tasks",
		contextWindow: 400000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 0.75, output: 4.5, cacheRead: 0.075, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: null, max: null },
	},
	{
		id: "google/gemini-3.8-flash",
		name: "Gemini 3.8 Flash",
		group: "Google",
		description: "newest Gemini Flash, improved core reasoning",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 1.5, output: 7.5, cacheRead: 0.15, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: null, max: null },
	},
	{
		id: "google/gemini-3.7-flash",
		name: "Gemini 3.7 Flash",
		group: "Google",
		description: "higher-quality coding & agentic workflows, fewer tokens",
		contextWindow: 1048576,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 1.5, output: 7.5, cacheRead: 0.15, cacheWrite: 0.08334 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: null, max: null },
	},
	{
		id: "google/gemini-3.6-flash",
		name: "Gemini 3.6 Flash",
		group: "Google",
		description: "previous Gemini Flash, still fast & capable",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 1.5, output: 7.5, cacheRead: 0.15, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: null, max: null },
	},
	{
		id: "google/gemini-3.5-flash",
		name: "Gemini 3.5 Flash",
		group: "Google",
		description: "Pro-level coding proficiency, parallel agentic execution",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 1.5, output: 9, cacheRead: 0.15, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: null, max: null },
	},
	{
		id: "google/gemini-3.5-flash-lite",
		name: "Gemini 3.5 Flash Lite",
		group: "Google",
		description: "upgraded agentic capabilities, ideal for subagents",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 0.3, output: 2.5, cacheRead: 0.03, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: null, max: null },
	},
	{
		id: "google/gemini-3.1-flash-lite",
		name: "Gemini 3.1 Flash Lite",
		group: "Google",
		description: "high-volume workhorse model with implicit caching",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 0.25, output: 1.5, cacheRead: 0.03, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: null, max: null },
	},
	{
		id: "sakana/fugu-ultra",
		name: "Fugu Ultra",
		group: "Sakana",
		description: "multi-agent orchestration across frontier models",
		contextWindow: 1000000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: null, medium: null, high: "high", xhigh: "xhigh", max: null },
	},
	{
		id: "meta/muse-spark-1.1",
		name: "Muse Spark 1.1",
		group: "Meta",
		description: "agentic performance, tool use, and computer use",
		contextWindow: 1048576,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 1.25, output: 4.25, cacheRead: 0.15, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: "xhigh", max: null },
	},
	{
		id: "meta/muse-spark-1.2",
		name: "Muse Spark 1.2",
		group: "Meta",
		description: "coding-optimized for agentic workflows and large codebases",
		contextWindow: 1048576,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 1.25, output: 4.25, cacheRead: 0.15, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: "xhigh", max: null },
	},
	{
		id: "meta/muse-spark-1.2-contributor",
		name: "Muse Spark 1.2 Contributor",
		group: "Meta",
		description: "Muse Spark 1.2 at ~95% off",
		contextWindow: 1048576,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 0.1, output: 0.2, cacheRead: 0.002, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: "xhigh", max: null },
	},
	{
		id: "meta/muse-spark-1.3",
		name: "Muse Spark 1.3",
		group: "Meta",
		description: "multimodal reasoning for long-horizon agentic and coding workflows",
		contextWindow: 1048576,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 1.25, output: 4.25, cacheRead: 0.15, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: "xhigh", max: "max" },
	},
	{
		id: "meta/muse-spark-1.3-contributor",
		name: "Muse Spark 1.3 Contributor",
		group: "Meta",
		description: "Muse Spark 1.3 at up to 95% off",
		contextWindow: 1048576,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 0.1, output: 0.2, cacheRead: 0.002, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: "xhigh", max: null },
	},
	{
		id: "xai/grok-4.5",
		name: "Grok 4.5",
		group: "xAI",
		description: "smartest model for coding, agentic tasks, knowledge work",
		contextWindow: 500000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 2, output: 6, cacheRead: 0.5, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: null, max: null },
	},
	{
		id: "xai/grok-4.6",
		name: "Grok 4.6",
		group: "xAI",
		description: "frontier performance on coding, knowledge work, and STEM",
		contextWindow: 500000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 2, output: 6, cacheRead: 0.5, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: "xhigh", max: null },
	},
	{
		id: "xai/grok-4.7",
		name: "Grok 4.7",
		group: "xAI",
		description: "coding and knowledge work, built for multi-hour tasks",
		contextWindow: 500000,
		maxTokens: 64000,
		reasoning: true,
		input: ["text", "image"],
		cost: { input: 1.2, output: 3.6, cacheRead: 0.3, cacheWrite: 0 },
		thinkingLevelMap: { minimal: null, low: "low", medium: "medium", high: "high", xhigh: "xhigh", max: null },
	},
];

/** Build MyHarness models for every catalog entry. */
export function buildCommandCodeModels(): Model<CommandCodeApi>[] {
	return COMMAND_CODE_CATALOG.map((entry) => ({
		id: entry.id,
		name: entry.name,
		api: entry.group === "Anthropic" ? "anthropic-messages" : "openai-completions",
		provider: COMMAND_CODE_PROVIDER_ID,
		baseUrl: entry.group === "Anthropic" ? COMMAND_CODE_ANTHROPIC_BASE_URL : COMMAND_CODE_OPENAI_BASE_URL,
		reasoning: entry.reasoning,
		thinkingLevelMap: entry.thinkingLevelMap,
		input: entry.input,
		cost: entry.cost,
		contextWindow: entry.contextWindow,
		maxTokens: entry.maxTokens,
	}));
}

interface LiveCommandCodeModel {
	id?: unknown;
	name?: unknown;
	context_length?: unknown;
	supported_endpoints?: unknown;
}

function apiForSupportedEndpoints(endpoints: unknown): CommandCodeApi | undefined {
	if (!Array.isArray(endpoints) || endpoints.some((endpoint) => typeof endpoint !== "string")) return undefined;
	if (endpoints.includes("/chat/completions")) return "openai-completions";
	if (endpoints.includes("/messages")) return "anthropic-messages";
	return undefined;
}

/**
 * Map the live, public model list onto metadata this client has verified.
 * Unknown models are omitted until their capabilities and price data are known.
 */
export function mapCommandCodeModels(payload: unknown): Model<CommandCodeApi>[] {
	if (!payload || typeof payload !== "object" || !Array.isArray((payload as { data?: unknown }).data)) {
		throw new Error("Command Code returned an invalid model catalog");
	}

	const staticModels = new Map(buildCommandCodeModels().map((model) => [model.id, model]));
	const models: Model<CommandCodeApi>[] = [];
	for (const value of (payload as { data: unknown[] }).data) {
		if (!value || typeof value !== "object" || Array.isArray(value)) continue;
		const live = value as LiveCommandCodeModel;
		if (typeof live.id !== "string") continue;
		const known = staticModels.get(live.id);
		const api = apiForSupportedEndpoints(live.supported_endpoints);
		if (!known || !api) continue;
		const baseUrl = api === "anthropic-messages" ? COMMAND_CODE_ANTHROPIC_BASE_URL : COMMAND_CODE_OPENAI_BASE_URL;
		models.push({
			...known,
			api,
			baseUrl,
			...(typeof live.name === "string" && live.name.trim() ? { name: live.name } : {}),
			...(typeof live.context_length === "number" &&
			Number.isSafeInteger(live.context_length) &&
			live.context_length > 0
				? { contextWindow: live.context_length }
				: {}),
		});
	}
	if (models.length === 0) throw new Error("Command Code returned no supported models with known metadata");
	return models;
}
