// Core session management
export {
	AgentSession,
	type AgentSessionConfig,
	type AgentSessionEvent,
	type AgentSessionEventListener,
	type ModelCycleResult,
	type ParsedSkillBlock,
	type PromptAttachment,
	type PromptOptions,
	parseSkillBlock,
	type SessionStats,
} from "./agent/runtime/agent-session.ts";
export { convertToLlm } from "./agent/runtime/messages.ts";
export {
	createInitialRunSnapshot,
	isRunStateActive,
	isRunStateTerminal,
	RUN_STATE_LABELS,
	type RunState,
	type RunStateSnapshot,
} from "./agent/runtime/run-state.ts";
// SDK for programmatic usage
export {
	AgentSessionRuntime,
	type AgentSessionRuntimeDiagnostic,
	type AgentSessionServices,
	type CreateAgentSessionFromServicesOptions,
	type CreateAgentSessionOptions,
	type CreateAgentSessionResult,
	type CreateAgentSessionRuntimeFactory,
	type CreateAgentSessionRuntimeResult,
	type CreateAgentSessionServicesOptions,
	// Factory
	createAgentSession,
	createAgentSessionFromServices,
	createAgentSessionRuntime,
	createAgentSessionServices,
	createBashTool,
	// Tool factories (for custom cwd)
	createCodingTools,
	createEditTool,
	createFindTool,
	createGrepTool,
	createLsTool,
	createPwshTool,
	createReadOnlyTools,
	createReadTool,
	createSymbolsTool,
	createWriteTool,
	type PromptTemplate,
} from "./agent/runtime/sdk.ts";
export type { ResourceCollision, ResourceDiagnostic, ResourceLoader } from "./application/resource-loader.ts";
export { DefaultResourceLoader, loadProjectContextFiles } from "./application/resource-loader.ts";
export {
	type AddWorkspaceResult,
	findWorkspaceDataContext,
	getWorkspacesPath,
	normalizeWorkspaceRoot,
	type RelocateWorkspacesResult,
	resolveWorkspaceDataContext,
	validateWorkspacePath,
	type Workspace,
	type WorkspaceConsistencyIssue,
	type WorkspaceConsistencyIssueCode,
	type WorkspaceDataContext,
	WorkspaceStore,
} from "./application/workspace-store.ts";
export { type Args, parseArgs } from "./cli/args.ts";
export {
	BUILTIN_SLASH_COMMANDS,
	type BuiltinSlashCommand,
	type ExpandedBuiltinPromptCommand,
	expandBuiltinPromptCommand,
	parseExpandedBuiltinPromptCommand,
	parseSlashCommandInvocation,
	type SlashCommandInvocation,
} from "./cli/slash-commands.ts";
export {
	getSessionConversationPath,
	getSessionDir,
	getSessionMetadataPath,
	getSessionScopedDataDir,
	getWorkspaceDir,
	getWorkspaceMetadataPath,
	getWorkspaceRegistryPath,
	getWorkspaceScopedDataDir,
	getWorkspaceSessionsDir,
	getWorkspacesDir,
	parseSessionDataPath,
} from "./config/paths/index.ts";
export {
	type AutoMemorySettings,
	type CompactionSettings,
	type DefaultProjectTrust,
	type GitIntegrationSettings,
	type ImageSettings,
	type PackageSource,
	type ResolvedWebSearchSettings,
	type RetrySettings,
	SettingsManager,
	type SettingsManagerCreateOptions,
	type SubAgentSettings,
	type WebSearchSettings,
	type WebSearchStrategySettings,
} from "./config/settings/index.ts";
export {
	hasTrustRequiringProjectResources,
	type ProjectTrustDecision,
	ProjectTrustStore,
	type ProjectTrustStoreEntry,
	type ProjectTrustUpdate,
} from "./config/trust/index.ts";
// Config paths
export {
	CONFIG_DIR_NAME,
	getAgentDir,
	getDataDir,
	getDocsPath,
	getExamplesPath,
	getPackageDir,
	getReadmePath,
	getSessionsDir,
	VERSION,
} from "./config.ts";
// Compaction
export {
	type BranchPreparation,
	type BranchSummaryResult,
	type CollectEntriesResult,
	type CompactionResult,
	calculateContextTokens,
	collectEntriesForBranchSummary,
	compact,
	DEFAULT_COMPACTION_SETTINGS,
	estimateTokens,
	type FileOperations,
	type GenerateBranchSummaryOptions,
	generateBranchSummary,
	getLastAssistantUsage,
	prepareBranchEntries,
	serializeConversation,
	shouldCompact,
} from "./context/compact/index.ts";
export {
	CONTEXT_ATTACHMENT_CUSTOM_TYPE,
	type CommentAnchor,
	type CommentContextItem,
	type ContextItem,
	type ContextItemSummary,
	type ContextValidationResult,
	type DiffContextItem,
	type FileContextItem,
	fileContextItemFromPreview,
	formatContextItemsForPrompt,
	validateContextItems,
} from "./context/context-items.ts";
export {
	buildUnifiedText,
	type FileDiff,
	type FileDiffErrorCode,
	type FileDiffHunk,
	type FileDiffLine,
	type FileDiffLineKind,
	type FileDiffParams,
	type FileDiffResult,
	getFileDiff,
	MAX_DIFF_FILE_BYTES,
	MAX_DIFF_LINES,
	parseUnifiedDiff,
} from "./context/file-diff.ts";
// File Presentation / Diff / Context (Task 9)
export {
	BINARY_SNIFF_BYTES,
	type FilePreview,
	type FilePreviewErrorCode,
	type FilePreviewKind,
	type FilePreviewLine,
	type FilePreviewParams,
	type FilePreviewResult,
	type FilePreviewTruncation,
	formatSize as formatFileSize,
	getFilePreview,
	hashText,
	isBinaryBuffer,
	MAX_PREVIEW_FILE_BYTES,
	previewFile,
} from "./context/file-presentation.ts";
export {
	createExtensionRuntime,
	defineTool,
	discoverAndLoadExtensions,
	ExtensionRunner,
	isBashToolResult,
	isEditToolResult,
	isFindToolResult,
	isGrepToolResult,
	isLsToolResult,
	isReadToolResult,
	isToolCallEventType,
	isWriteToolResult,
	wrapRegisteredTool,
	wrapRegisteredTools,
} from "./extensions/compat/index.ts";
// Extension system
export type {
	AgentEndEvent,
	AgentResponseReadyEvent,
	AgentSettledEvent,
	AgentStartEvent,
	AgentToolResult,
	AgentToolUpdateCallback,
	AppKeybinding,
	AutocompleteProviderFactory,
	BashToolCallEvent,
	BeforeAgentStartEvent,
	BeforeAgentStartEventResult,
	BeforeProviderHeadersEvent,
	BeforeProviderRequestEvent,
	BeforeProviderRequestEventResult,
	BuildSystemPromptOptions,
	CompactOptions,
	ContextEvent,
	ContextUsage,
	CustomToolCallEvent,
	EditToolCallEvent,
	EntryRenderer,
	EntryRenderOptions,
	ExecOptions,
	ExecResult,
	Extension,
	ExtensionActions,
	ExtensionAPI,
	ExtensionCommandContext,
	ExtensionCommandContextActions,
	ExtensionContext,
	ExtensionContextActions,
	ExtensionError,
	ExtensionEvent,
	ExtensionFactory,
	ExtensionFlag,
	ExtensionHandler,
	ExtensionRuntime,
	ExtensionShortcut,
	ExtensionUIContext,
	ExtensionUIDialogOptions,
	ExtensionWidgetOptions,
	FindToolCallEvent,
	GrepToolCallEvent,
	InlineExtension,
	InputEvent,
	InputEventResult,
	InputSource,
	KeybindingsManager,
	LoadExtensionsResult,
	LsToolCallEvent,
	MessageEndEvent,
	MessageRenderer,
	MessageRenderOptions,
	MessageStartEvent,
	MessageUpdateEvent,
	ProjectTrustContext,
	ProjectTrustEvent,
	ProjectTrustEventDecision,
	ProjectTrustEventResult,
	ProjectTrustHandler,
	ProviderConfig,
	ProviderModelConfig,
	ReadToolCallEvent,
	RegisteredCommand,
	RegisteredTool,
	ResolvedCommand,
	SessionBeforeCompactEvent,
	SessionBeforeForkEvent,
	SessionBeforeSwitchEvent,
	SessionBeforeTreeEvent,
	SessionCompactEvent,
	SessionInfoChangedEvent,
	SessionShutdownEvent,
	SessionStartEvent,
	SessionTreeEvent,
	SlashCommandInfo,
	SlashCommandSource,
	SourceInfo,
	TerminalInputHandler,
	ToolCallEvent,
	ToolCallEventResult,
	ToolDefinition,
	ToolExecutionEndEvent,
	ToolExecutionMode,
	ToolExecutionStartEvent,
	ToolExecutionUpdateEvent,
	ToolInfo,
	ToolRenderResultOptions,
	ToolResultEvent,
	TurnEndEvent,
	TurnStartEvent,
	UserBashEvent,
	UserBashEventResult,
	WidgetPlacement,
	WorkingIndicatorOptions,
	WriteToolCallEvent,
} from "./extensions/compat/types.ts";
export { createSyntheticSourceInfo } from "./extensions/contracts/source-info.ts";
export type {
	PackageManager,
	PathMetadata,
	ProgressCallback,
	ProgressEvent,
	ResolvedPaths,
	ResolvedResource,
} from "./extensions/packages/package-manager.ts";
export { DefaultPackageManager } from "./extensions/packages/package-manager.ts";
export { createEventBus, type EventBus, type EventBusController } from "./extensions/runtime/event-bus.ts";
export {
	beginRepositoryDirectoryMove,
	deleteLocalGitRepositoryMetadata,
	getLocalGitRepositoriesPath,
	getMovedRepositoryPath,
	getRenamedRepositoryPath,
	initializeManagedLocalGitRepository,
	inspectLocalGitRepositoryPath,
	type LocalGitRepository,
	type LocalGitRepositoryResult,
	type LocalGitRepositoryStatus,
	LocalGitRepositoryStore,
	selectLocalGitRepository,
	validateLocalGitDirectory,
} from "./git/local-repositories/store.ts";
// Main entry point
export { type MainOptions, main } from "./main.ts";
// Run modes for programmatic SDK usage
export {
	InteractiveMode,
	type InteractiveModeOptions,
	type PrintModeOptions,
	runPrintMode,
} from "./modes/index.ts";
// UI components for extensions
export {
	AssistantMessageComponent,
	BashExecutionComponent,
	BorderedLoader,
	BranchSummaryMessageComponent,
	CompactionSummaryMessageComponent,
	CustomEditor,
	CustomMessageComponent,
	DynamicBorder,
	ExtensionEditorComponent,
	ExtensionInputComponent,
	ExtensionSelectorComponent,
	FooterComponent,
	keyHint,
	keyText,
	ModelSelectorComponent,
	type RenderDiffOptions,
	rawKeyHint,
	renderDiff,
	SessionSelectorComponent,
	type SettingsCallbacks,
	type SettingsConfig,
	SettingsSelectorComponent,
	ShowImagesSelectorComponent,
	SkillInvocationMessageComponent,
	ThemeSelectorComponent,
	ThinkingSelectorComponent,
	ToolExecutionComponent,
	type ToolExecutionOptions,
	truncateToVisualLines,
	UserMessageComponent,
	type VisualTruncateResult,
} from "./modes/interactive/components/index.ts";
// Footer data provider (git branch + extension statuses - data not otherwise available to extensions)
export type { ReadonlyFooterDataProvider } from "./modes/interactive/footer-data-provider.ts";
// Theme utilities for custom tools and extensions
export {
	getLanguageFromPath,
	getMarkdownTheme,
	getSelectListTheme,
	getSettingsListTheme,
	highlightCode,
	initTheme,
	Theme,
	type ThemeColor,
} from "./modes/interactive/theme/theme.ts";
export type {
	ApiKeyCollectionStore,
	ProviderCredentialOverview,
	StoredApiKeyInfo,
} from "./providers/credentials/api-key-collection.ts";
export { readStoredCredential } from "./providers/credentials/auth-storage.ts";
export { ModelRegistry } from "./providers/models/registry.ts";
export {
	type CreateModelRuntimeOptions,
	type ModelCredentialUsage,
	ModelRuntime,
	type ModelRuntimeAuthOverrides,
} from "./providers/runtime/index.ts";
export {
	type ModelScopeDiagnostic,
	type ResolveCliModelResult,
	type ResolveModelScopeResult,
	resolveCliModel,
	resolveModelScopeWithDiagnostics,
	type ScopedModel,
} from "./providers/runtime/model-resolver.ts";
export {
	type BranchSummaryEntry,
	buildContextEntries,
	buildSessionContext,
	type CompactionEntry,
	CURRENT_SESSION_VERSION,
	type CustomEntry,
	type CustomMessageEntry,
	type FileEntry,
	getLatestCompactionEntry,
	type ModelChangeEntry,
	migrateSessionEntries,
	type NewSessionOptions,
	parseSessionEntries,
	type SessionContext,
	type SessionEntry,
	type SessionEntryBase,
	type SessionHeader,
	type SessionInfo,
	type SessionInfoEntry,
	type SessionJsonlDiagnostic,
	type SessionJsonlDiagnostics,
	type SessionJsonlIssueKind,
	SessionManager,
	type SessionManagerStorageOptions,
	type SessionMessageEntry,
	type SessionTreeNode,
	sessionEntryToContextMessages,
	type ThinkingLevelChangeEntry,
} from "./session/manager/index.ts";
// Skills
export {
	formatSkillsForPrompt,
	type LoadSkillsFromDirOptions,
	type LoadSkillsResult,
	loadSkills,
	loadSkillsFromDir,
	type Skill,
	type SkillFrontmatter,
} from "./skills/loader/index.ts";
// Code Intelligence 统一数据模型（第 2 阶段）：供未来 Lightweight / Semantic Backend
// 与 Symbol Store 共用。旧索引格式类型以 IndexedCodeSymbol / IndexedCodeReference 导出。
export {
	buildNamePath,
	type CodeDiagnostic,
	type CodeLocation,
	type CodePosition,
	type CodeRange,
	type CodeReference,
	type CodeReferenceKind,
	type CodeSymbol,
	type CodeSymbolKind,
	type CodeSymbolTreeNode,
	convertLegacySymbol,
	convertLegacySymbols,
	createSymbolId,
	type DefinitionResult,
	type DiagnosticSeverity,
	type DiagnosticsResult,
	type FileSymbolsResult,
	getParentNamePath,
	type ImplementationsResult,
	type IntelligenceResult,
	type IntelligenceResultMeta,
	type IntelligenceSource,
	type LegacyConversionOptions,
	NAMEPATH_SEPARATOR,
	normalizeSymbolPath,
	type ParsedNamePath,
	parseNamePath,
	type ReferencesResult,
	type ResultCompleteness,
	type SymbolId,
	type SymbolIdInput,
	type SymbolQuery,
	type SymbolSearchResult,
	type SymbolTarget,
	type SymbolVisibility,
} from "./symbols/api.ts";
export {
	type CodeIndexOptions,
	type CodeIndexRefreshSummary,
	type CodeIndexStats,
	type CodeMapEntry,
	type CodeSearchMatch,
	type CodeSearchOptions,
	CodeSymbolIndex,
	getCodeIndexPath,
	getCodeLanguage,
	type IndexedCodeReference,
	type IndexedCodeSymbol,
	type IndexedCodeSymbolKind,
	parseCodeSymbols,
} from "./symbols/index/code-index.ts";
export type { ThemeResource } from "./themes/loader/theme-resource.ts";
export type { BusinessToolDefinition } from "./tools/contracts/index.ts";
export { type EditDiffResult, generateDiffString, generateUnifiedPatch } from "./tools/files/edit-diff.ts";
export {
	createBashToolDefinition,
	createEditToolDefinition,
	createFindToolDefinition,
	createGrepToolDefinition,
	createLsToolDefinition,
	createPwshToolDefinition,
	createReadToolDefinition,
	createSubAgentToolDefinition,
	createSymbolsToolDefinition,
	createWorkflowToolDefinition,
	createWriteToolDefinition,
} from "./tools/presentation/public.ts";
// Tools
export {
	type BashOperations,
	type BashSpawnContext,
	type BashSpawnHook,
	type BashToolDetails,
	type BashToolInput,
	type BashToolOptions,
	createLocalBashOperations,
	createLocalPwshOperations,
	createSubAgentTool,
	createWebFetchTool,
	createWebFetchToolDefinition,
	createWebResearchTool,
	createWebResearchToolDefinition,
	createWebSearchTool,
	createWebSearchToolDefinition,
	createWebSearchToolDefinitions,
	createWorkflowTool,
	DEFAULT_MAX_BYTES,
	DEFAULT_MAX_LINES,
	type EditOperations,
	type EditToolDetails,
	type EditToolInput,
	type EditToolOptions,
	type FindOperations,
	type FindToolDetails,
	type FindToolInput,
	type FindToolOptions,
	formatSize,
	type GrepOperations,
	type GrepToolDetails,
	type GrepToolInput,
	type GrepToolOptions,
	type LsOperations,
	type LsToolDetails,
	type LsToolInput,
	type LsToolOptions,
	type PwshOperations,
	type PwshSpawnContext,
	type PwshSpawnHook,
	type PwshToolDetails,
	type PwshToolInput,
	type PwshToolOptions,
	type ReadOperations,
	type ReadToolDetails,
	type ReadToolInput,
	type ReadToolOptions,
	type SubAgentBackgroundProgress,
	type SubAgentBackgroundTask,
	type SubAgentRuntimeSettings,
	type SubAgentTaskSpec,
	type SubAgentToolDetails,
	type SubAgentToolInput,
	type SubAgentToolOptions,
	type SubAgentToolTrace,
	type SymbolsCodeIntelligenceServices,
	type SymbolsIndexPort,
	SymbolsToolConfigurationError,
	type SymbolsToolDetails,
	type SymbolsToolInput,
	SymbolsToolInputError,
	type SymbolsToolOptions,
	type SymbolsToolTarget,
	type ToolsOptions,
	type TruncationOptions,
	type TruncationResult,
	truncateHead,
	truncateLine,
	truncateTail,
	type WebFetchToolDetails,
	type WebFetchToolInput,
	type WebResearchToolDetails,
	type WebResearchToolInput,
	type WebSearchToolDetails,
	type WebSearchToolInput,
	type WebSearchToolOptions,
	type WorkflowPhaseDetails,
	type WorkflowToolDetails,
	type WorkflowToolInput,
	type WorkflowToolOptions,
	type WriteOperations,
	type WriteToolInput,
	type WriteToolOptions,
	withFileMutationQueue,
} from "./tools/registry.ts";
// Clipboard utilities
export { copyToClipboard } from "./utils/clipboard.ts";
export { parseFrontmatter, stripFrontmatter } from "./utils/frontmatter.ts";
export { convertToPng } from "./utils/image-convert.ts";
export { formatDimensionNote, type ResizedImage, resizeImage } from "./utils/image-resize.ts";
// Shell utilities
export { getShellConfig } from "./utils/shell.ts";
